version: "3.8"

services:
  db:
    image: postgres:14.6
    container_name: postgresql_backend_backendbydips3_186
    environment:
      - PGHOST=<<DB_HOST>>
      - POSTGRES_USER=<<DB_USER>>
      - POSTGRES_PASSWORD=<<DB_PASSWORD>>
    volumes:
      - ./create-schema.sql:/create-schema.sql
      # - ./db:/var/lib/postgresql/data
    command: <<SCHEMA_CREATION_CMD>>

  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 8088:8080
    environment:
      - spring.profiles.active=dev
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://<<DB_HOST>>:<<DB_PORT>>/postgres?currentSchema=backendbydips3
      - spring.datasource.username=<<DB_USER>>
      - spring.datasource.password=<<DB_PASSWORD>>
      - spring.jpa.properties.hibernate.default_schema=backendbydips3
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
